SET SQLBLANKLINES ON
CREATE TABLE SMARTCO.MIS_PB_SA_PORTA_BLOQUEADA 
(
  DATA_BASE DATE 
, REGIONAL VARCHAR2(12 BYTE) 
, CIDADE VARCHAR2(30 BYTE) 
, UF VARCHAR2(2 BYTE) 
, ARMARIO VARCHAR2(11 BYTE) 
, PORTA_VOZ VARCHAR2(30 BYTE) 
, ID_PORTA_VOZ VARCHAR2(50 BYTE) 
, MOTIVO_BLOQUEIO_VOZ VARCHAR2(30 BYTE) 
, COMENTARIOS_VOZ VARCHAR2(300 BYTE) 
, DATA_BLOQUEIO_VOZ DATE 
, RIN VARCHAR2(20 BYTE) 
, PORTA_BANDA VARCHAR2(30 BYTE) 
, MOTIVO_BLOQUEIO_BANDA VARCHAR2(30 BYTE) 
, COMENTARIOS_BANDA VARCHAR2(300 BYTE) 
, DATA_BLOQUEIO_BANDA DATE 
) 
LOGGING 
TABLESPACE REPOSITORY 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE SMARTCO.MIS_PB_TD001_DETALHE_BLOQUEIO 
(
  ID NUMBER 
, PRODUTO VARCHAR2(50) 
, MOTIVO VARCHAR2(50) NOT NULL 
, SUBMOTIVO VARCHAR2(50) NOT NULL 
);

CREATE TABLE SMARTCO.MIS_PB_TF001_PORTA_BLOQUEADA 
(
  ID NUMBER NOT NULL 
, ID_PORTA_VOZ VARCHAR2(50) NOT NULL 
, LOCALIDADE_FK NUMBER NOT NULL 
, DETALHE_BLOQUEIO_FK NUMBER NOT NULL 
, CONSTRAINT MIS_PB_TF001_PORTA_BLOQUEA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE SMARTCO.MIS_TD002_TEMPO 
(
  DAY_ID DATE 
, DAY_TIME_SPAN NUMBER 
, DAY_END_DATE DATE 
, WEEK_DAY_FULL VARCHAR2(52 BYTE) 
, WEEK_DAY_SHORT VARCHAR2(12 BYTE) 
, DAY_NUM_OF_WEEK NUMBER 
, DAY_NUM_OF_MONTH NUMBER 
, DAY_NUM_OF_YEAR NUMBER 
, MONTH_ID VARCHAR2(17 BYTE) 
, MONTH_TIME_SPAN NUMBER 
, MONTH_END_DATE DATE 
, MONTH_SHORT_DESC VARCHAR2(17 BYTE) 
, MONTH_LONG_DESC VARCHAR2(41 BYTE) 
, MONTH_SHORT VARCHAR2(12 BYTE) 
, MONTH_LONG VARCHAR2(36 BYTE) 
, MONTH_NUM_OF_YEAR NUMBER 
, QUARTER_ID VARCHAR2(7 BYTE) 
, QUARTER_TIME_SPAN NUMBER 
, QUARTER_END_DATE DATE 
, QUARTER_NUM_OF_YEAR NUMBER 
, HALF_NUM_OF_YEAR NUMBER 
, HALF_OF_YEAR_ID VARCHAR2(7 BYTE) 
, HALF_YEAR_TIME_SPAN NUMBER 
, HALF_YEAR_END_DATE DATE 
, YEAR_ID VARCHAR2(4 BYTE) 
, YEAR_TIME_SPAN NUMBER 
, YEAR_END_DATE DATE 
) 
LOGGING 
TABLESPACE REPOSITORY 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 4194304 
  NEXT 4194304 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE SMARTCO.MIS_TD003_LOCALIDADE 
(
  ID NUMBER NOT NULL 
, PAIS VARCHAR2(50) NOT NULL 
, REGIONAL VARCHAR2(50) NOT NULL 
, ESTADO VARCHAR2(50) NOT NULL 
, CLSTR VARCHAR2(50) NOT NULL 
, CIDADE VARCHAR2(50) NOT NULL 
, ARMARIO VARCHAR2(50) NOT NULL 
, CONSTRAINT MIS_TD003_LOCALIDADE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE UNIQUE INDEX SMARTCO.MIS_TD003_LOCALIDADE_INDEX ON SMARTCO.MIS_TD003_LOCALIDADE (ARMARIO ASC);

ALTER TABLE SMARTCO.MIS_PB_TF001_PORTA_BLOQUEADA
ADD CONSTRAINT DETALHE_BLOQUEIO_FK FOREIGN KEY
(
  )
REFERENCES SMARTCO.MIS_PB_TD001_DETALHE_BLOQUEIO
(
  )
ENABLE;

COMMENT ON COLUMN SMARTCO.MIS_PB_TF001_PORTA_BLOQUEADA.ID_PORTA_VOZ IS 'Surrugate Key';
